### ISSUE TITLE
Inconsistent aerial cut back movement :: max speed bug

### ISSUE THREAD

**Issue by scottnm** [nanomachines/filibusters-game#114]
![maxspeedbug](https://cloud.githubusercontent.com/assets/5483270/18700347/67c5137a-7f9c-11e6-933c-1bfc50d656ba.gif)

**Comment by scottnm** [comment]
So to make this super noticeable I scaled the movement and aerial speed by 2.5x. You can see that if I start moving right on the ground and then jump in the air and hook back left, I can get some considerable distance. This isn't the case for if I move left first and try and jump in the air and hook back to the right

**Comment by phoenixbishea** [comment]
This may be fixed with the absolute value check. I haven't tested yet.

**Comment by scottnm** [comment]
Just did a rudimentary test and it seems to work much better with your change on aa54a610798896e6e033aee653a276c3cb18feb5

Do some testing yourself and if everything is a-ok then we can close this issue :)
