### ISSUE TITLE
Build a simple placeholder world with collision boxes and placeholder assets

### ISSUE THREAD

**Issue by scottnm** [nanomachines/filibusters-game#16]

**Comment by tsurles** [comment]
![coin 0](https://cloud.githubusercontent.com/assets/21988534/18292618/d6845fe0-7453-11e6-832e-1e7dc6979fc3.png)
![ballot box 0 1](https://cloud.githubusercontent.com/assets/21988534/18292624/dd4d4a6c-7453-11e6-9d51-e8175e642a0c.png)

**Comment by tsurles** [comment]
![creat 0](https://cloud.githubusercontent.com/assets/21988534/18292771/a110fd7c-7454-11e6-9c99-2dc63025c4c7.png)
