### ISSUE TITLE
variable aspect ratios affect how much of the ready room that the player sees

### ISSUE THREAD

**Issue by scottnm** [nanomachines/filibusters-game#246]

**Comment by phoenixbishea** [comment]
We will need to bring the camera out and possibly shrink the scene.

**Comment by phoenixbishea** [comment]
We should also have a background (vs plain black) for larger aspect ratios (maybe the skyline connor is working on).

**Comment by phoenixbishea** [comment]
Changing the camera size to 12 fixes it. We need to always remember to build for the smallest aspect ratio.
