### ISSUE TITLE
Magic bullet animation bullet problems.

### ISSUE THREAD

**Issue by tsurles** [nanomachines/filibusters-game#294]
Magic bullet animation occasionally does not update to other players who did not shoot the bullet. For example, if bullet is shot to the left, occasionally when it reflects off the wall, the bullet's animation won't adjust to the new direction and while going to the right, and therefore still be facing like it is going left. Again, seems to be something that only happens if you aren't the player shooting the bullet at the time. Discovered by Alex and Thomas if anyone has further questions.

**Comment by scottnm** [comment]
I think I saw something similar to that when toprac was playtesting last wednesday! Will investigateater tonight
