### ISSUE TITLE
As a sound engineer, I want to find audio cues for punching, coin collection, and coin depositing so that players will have audio-visual feedback

### ISSUE THREAD

**Issue by phoenixbishea** [nanomachines/filibusters-game#30]
If you have a chance Thomas, find a few free audio cues for these noises and add them to the repo. One of the engineers will put them in.

**Comment by tsurles** [comment]
Issue, .wav formatting isn't an acceptable file type for github, so I put them in a google drive, let me know if you cant access it.
https://drive.google.com/a/utexas.edu/folderview?id=0B8hZ59gyr7UlOVZLQk1zODNuNFE&usp=sharing

**Comment by scottnm** [comment]
That's very strange. GitHub should be file agnostic so it shouldn't matter
what kind of file you try and upload. We should take a look into this the
next time we meet up
