### ISSUE TITLE
Tutorial coin respawn bug #2

### ISSUE THREAD

**Issue by tsurles** [nanomachines/filibusters-game#305]
The host player was in the game and had deposit their coin. player two then joined and player one dropped out. Player two then deposited the coin while host player was gone and host player went to join the game. Both the host players coin and the second player's coin respawned and did not allow the game to start.Player 2 could not see the coin in their room however. To try to fix this problem player two dropped and rejoined the game. The coin remained in player two's area, however, the start game prompt was given.  Upon depositing the coin, the prompt went away and the players were unable to continue.

Thomas hosted and Alex was player two when this bug was found.

**Comment by scottnm** [comment]
duplicate #303
